CFLAGS ?= -O2 -std=c++98 -Wall -Wextra -Iinclude

ALL = NegativeGraphDiv1

all: $(ALL)

clean:
	rm -f NegativeGraphDiv1

NegativeGraphDiv1: NegativeGraphDiv1.cpp
	g++ $(CFLAGS) -o NegativeGraphDiv1 NegativeGraphDiv1.cpp
